version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'vitest*'
          - 'playwright*'
        update-types:
          - 'minor'
          - 'patch'
      production-minor-patch:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
